# Generated by Django 5.1.6 on 2025-11-02 02:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTransaction',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('pending', 'Pending'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('requires_action', 'Requires Action'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=50)),
                ('receipt_file_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Customer Transactions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('personalized_mentorship', 'Personalized Mentorship'), ('course_access', 'Course Access')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('currency_mutltiplier_to_stripe_unit', models.IntegerField(default=100)),
                ('details', models.JSONField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CustomerTransactionProduct',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='billing.customertransaction')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.product')),
            ],
            options={
                'verbose_name_plural': 'Customer Transaction Products',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_customer_id', models.CharField(max_length=255, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stripe Customers',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='customertransaction',
            name='stripe_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.stripecustomer'),
        ),
        migrations.CreateModel(
            name='StripeCustomerPaymentMethod',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method_id', models.CharField(max_length=255, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=100)),
                ('last4', models.CharField(max_length=4)),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('stripe_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='billing.stripecustomer')),
            ],
            options={
                'verbose_name_plural': 'Payment Methods for Stripe Customers',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserBilling',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_name', models.CharField(max_length=255)),
                ('billing_country', models.CharField(max_length=255)),
                ('billing_state', models.CharField(max_length=255)),
                ('billing_city', models.CharField(max_length=255)),
                ('billing_address', models.CharField(max_length=255)),
                ('billing_zipcode', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Billing for Users',
                'ordering': ('id',),
            },
        ),
    ]
