# Generated by Django 5.1.6 on 2025-09-24 15:10

import core.models.base_model
import core.utils.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, storage=core.models.base_model.MediaFileS3Storage(bucket_name='media', is_public=True), upload_to=core.utils.helpers.get_media_upload_path),
        ),
    ]
