# Generated by Django 5.1.6 on 2025-10-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file_type',
            field=models.CharField(choices=[('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO'), ('PDF', 'PDF'), ('CSV', 'CSV'), ('AUDIO', 'AUDIO'), ('OTHER', 'OTHER')], max_length=256),
        ),
        migrations.AlterField(
            model_name='media',
            name='post_type',
            field=models.CharField(choices=[('BLOG', 'BLOG'), ('TIP', 'TIP'), ('PROJECT', 'PROJECT'), ('COURSE', 'COURSE'), ('TESTIMONIAL', 'TESTIMONIAL'), ('GENERAL', 'GENERAL')], max_length=256),
        ),
    ]
